name: tpc_content_hub
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_plus: ^1.5.0
  shelf_router: ^1.1.3
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
